sudo: false
language: node_js
node_js:
  - 10
  - stable

before_install:
  - npm install -g npm

services:
  - xvfb

script:
  - yarn lint
  - yarn test

addons:
  firefox: 'latest'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_EVENT_TYPE=$TRAVIS_EVENT_TYPE TRAVIS_NODE_VERSION=$TRAVIS_NODE_VERSION" 
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_NODE_VERSION" == "stable" ]]; then
      semantic-release;
    fi;
